# For more information, see: https://github.com/commercialhaskell/stack/blob/release/doc/yaml_configuration.md

# Specifies the GHC version and set of packages available (e.g., lts-3.5, nightly-2015-09-21, ghc-7.10.2)
resolver: lts-6.10

ghc-options:
  agile-cli: -Werror -Wall -fno-warn-name-shadowing -fno-warn-orphans -fno-warn-type-defaults

# Packages to be pulled from upstream that are not in the resolver (e.g., acme-missiles-0.3)
extra-deps: 
# JIRA API library
- git: https://github.com/dsmatter/jira-api.git
  commit: 2dabd33d800a3f5fa1b0c8bbe145ceb6fb0d2bed
# Snapshot of github library (pre-version 0.14.0)
- git: https://github.com/phadej/github.git
  commit: a31e3652d0dcfbc4a420b7363877e25b113b3d2b
- regexpr-0.5.4
- mtlparse-0.1.4.0

# Override default flag values for local packages and extra-deps
flags:
  github:
    aeson-compat: true

# Extra package databases containing global packages
extra-package-dbs: []

# Control whether we use the GHC we find on the path
# system-ghc: true

# Require a specific version of stack, using version ranges
# require-stack-version: -any # Default
# require-stack-version: >= 1.0.0

# Override the architecture used by stack, especially useful on Windows
# arch: i386
# arch: x86_64

# Extra directories used by stack for building
extra-include-dirs: [/usr/local/opt/openssl/include]
extra-lib-dirs: [/usr/local/opt/openssl/lib]
